FROM ubuntu:16.04
# FROM arm=armhf/ubuntu:16.04

ARG DAPPER_HOST_ARCH
ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}

RUN apt-get update && \
    apt-get install -y python-pip jq && \
    && pip install awscli && \
    rm -f /bin/sh && ln -s /bin/bash /bin/sh

ENV DAPPER_ENV REPO TAG DRONE_TAG
ENV DAPPER_SOURCE /source
ENV DAPPER_OUTPUT ./dist
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
